// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnPlanStep } from "./TurnPlanStep";

export type TurnPlanSnapshot = { explanation: string | null, plan: Array<TurnPlanStep>,
/**
 * Opaque identity for this checklist update, or `null` for legacy data.
 */
revision: string | null,
/**
 * Unix timestamp (seconds) when this update was accepted, or `null` when unavailable.
 */
updatedAt: number | null, };
